const menu = [
    {
        id: 1,
        title: 'chapati',
        category: 'breakfast',
        price: 50,
        img: './images/1.jpeg',
        desc: 'fluffy milk pancakes',
    },
    {
        id: 2,
        title: 'chocolate milkshake',
        category: 'shakes',
        price: 499,
        img: './images/2.jpeg',
        desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
        id: 3,
        title: 'cookie milkshake',
        category: 'shakes',
        price: 600,
        img: './images/item-3.jpeg',
        desc: `chocolate cookie milkshake`,
    },
    {
        id: 4,
        title: 'English breakfast',
        category: 'breakfast',
        price: 800,
        img: './images/4.jpeg',
        desc: `full english breakfast `,
    },
    {
        id: 5,
        title: 'Fish with rice',
        category: 'lunch',
        price: 2000,
        img: './images/5.jpeg',
        desc: `garlic fish with white coconut rice`,
    },
    {
        id: 6,
        title: 'Fried Potatoes with beef',
        category: 'shakes',
        price: 800,
        img: './images/6.jpg',
        desc: `garlic and butter fried potatoes with beef`,
    },
    {
        id: 7,
        title: 'bacon overflow',
        category: 'breakfast',
        price: 8.99,
        img: './images/item-7.jpeg',
        desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
        id: 8,
        title: 'milk pancakes',
        category: 'breakfast',
        price: 400,
        img: './images/8.jpg',
        desc: `milk pancakes with strawberry`,
    },
    {
        id: 9,
        title: 'samosa',
        category: 'snacks',
        price: 80,
        img: './images/9.jpeg',
        desc: `chilli samosas`,
    },
];
export default menu;
